# Generated by Django 4.2.11 on 2024-03-05 03:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=1000)),
                ('deadlineDay', models.DateField()),
                ('deadlineTime', models.TimeField()),
                ('duration', models.DurationField()),
                ('status', models.BooleanField()),
                ('category', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='calendar_app.category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calendar_app.user')),
            ],
        ),
    ]
