# Generated by Django 4.2.10 on 2024-03-25 20:58

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='color',
            field=colorfield.fields.ColorField(default='#0d6efd', image_field=None, max_length=25, samples=None),
        ),
    ]
